/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   interface.h                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mbeckert <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/09/15 18:40:23 by mbeckert          #+#    #+#             */
/*   Updated: 2018/09/15 18:40:25 by mbeckert         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef INTERFACE_H
# define INTERFACE_H

# include <SDL2/SDL.h>

# define X_WIN_I (600)
# define Y_WIN_I (1080)

enum			e_value
{
	VO_POS_X,
	VO_POS_Y,
	VO_POS_Z,
	VO_AMBIENT_RED,
	VO_AMBIENT_GREEN,
	VO_AMBIENT_BLUE,
	VO_DIFFUSE_RED,
	VO_DIFFUSE_GREEN,
	VO_DIFFUSE_BLUE,
	VO_SPECULAR_RED,
	VO_SPECULAR_GREEN,
	VO_SPECULAR_BLUE,
	VO_TRANSPARENCY,
	VO_RAY,
	VO_SHININESS,
	VO_ALPHA,
	VC_POS_X,
	VC_POS_Y,
	VC_POS_Z,
	VC_FOV,
	VL_POS_X,
	VL_POS_Y,
	VL_POS_Z,
	VL_COLOR_RED,
	VL_COLOR_GREEN,
	VL_COLOR_BLUE,
	VL_RAY,
	VL_INTENSITY,
	VALUE_ALL,
	V_CUR_SCENE,
	V_CUR_CAM,
	V_CUR_OBJ,
	V_CUR_LIGHT,
	V_GO_HOME,
	V_GO_EDIT,
	V_GO_OBJECT,
	V_GO_OTHER,
	V_GO_LIGHT,
	V_REFRESH,
	VT_EDGE_HARD,
	VT_SHARPEN,
	VT_BLUR_BOX,
	VT_EMBOSSING,
	VT_ANTIALIAZ,
	VT_BLACK_WHITE,
	VT_SEPIA,
	VT_CARTOON,
	VT_TEXTURE,
	VT_CHECKER,
	VT_PERLIN,
	VT_NORMAL,
	V_TAKE_XML,
	V_TAKE_SCREEN
};

enum			e_rndr
{
	RNDR_1,
	RNDR_ALL
};

typedef struct	s_picture
{
	int		n_type;
	int		h_type;
	char	*n_path;
	char	*h_path;
}				t_picture;

typedef struct	s_text
{
	char		*font;
	char		*text;
	int			size;
	SDL_Rect	rect;
}				t_text;

# define TYPE_SVG		(1 << 0)
# define TYPE_BMP		(1 << 1)
# define TYPE_PNG		(1 << 2)

# define BACKGROUND		(3)

/*
** I_LIGHT,
** I_AMBIENT,
** I_SUN,
**
** a ajouter entre I_SPHERE_P et I_OTHER
*/

enum			e_interface
{
	I_HOME,
	I_ADD,
	I_CYLINDER_P,
	I_PLANE_P,
	I_CONE_P,
	I_DISK_P,
	I_SPHERE_P,
	I_OTHER,
	INTERFACE_ALL
};

static const t_picture g_background[BACKGROUND] = {
	(t_picture){.n_type = TYPE_BMP,
		.n_path = "./srcs/utils/interface.bmp"},
	(t_picture){.n_type = TYPE_BMP,
		.n_path = "./srcs/utils/interface_b.bmp"},
	(t_picture){.n_type = TYPE_BMP,
		.n_path = "./srcs/utils/interface_c.bmp"},
};

# define HOME_TEXT		(9)

static const t_text g_home_text[HOME_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 50,
		.text = "Home",
		.rect = (SDL_Rect){.x = 240, .y = 25}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 35,
		.text = "Ray_Tracer",
		.rect = (SDL_Rect){.x = 220, .y = 100}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 35,
		.text = "Change your Scene",
		.rect = (SDL_Rect){.x = 165, .y = 225}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 35,
		.text = "Change your Camera",
		.rect = (SDL_Rect){.x = 160, .y = 480}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 35,
		.text = "Edition Mode",
		.rect = (SDL_Rect){.x = 200, .y = 750}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 20,
		.text = "Yokartou",
		.rect = (SDL_Rect){.x = 155, .y = 1040}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 20,
		.text = "Mbeckert",
		.rect = (SDL_Rect){.x = 255, .y = 1040}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 20,
		.text = "Arguerin",
		.rect = (SDL_Rect){.x = 355, .y = 1040}},
};

# define ADD_TEXT		(4)

static const t_text g_add_text[ADD_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
		.text = "Choose your preference settings",
		.rect = (SDL_Rect){.x = 80, .y = 50}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 35,
		.text = "Edit objects",
		.rect = (SDL_Rect){.x = 350, .y = 225}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 35,
		.text = "Edit light sources",
		.rect = (SDL_Rect){.x = 100, .y = 560}},
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 35,
		.text = "Edit more options",
		.rect = (SDL_Rect){.x = 300, .y = 855}}};

# define CYLINDER_TEXT		(17)

static const t_text g_cylinder_p_text[CYLINDER_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
		.text = "Cylinder",
		.rect = (SDL_Rect){.x = 75, .y = 140}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object position",
		.rect = (SDL_Rect){.x = 25, .y = 220}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Position :",
		.rect = (SDL_Rect){.x = 50, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "x",
		.rect = (SDL_Rect){.x = 200, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "y",
		.rect = (SDL_Rect){.x = 300, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "z",
		.rect = (SDL_Rect){.x = 400, .y = 280}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object colors",
		.rect = (SDL_Rect){.x = 25, .y = 335}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Ambient Color :",
		.rect = (SDL_Rect){.x = 50, .y = 400}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Diffuse Color :",
		.rect = (SDL_Rect){.x = 50, .y = 460}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Speculaire Color :",
		.rect = (SDL_Rect){.x = 50, .y = 517}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object radius",
		.rect = (SDL_Rect){.x = 25, .y = 570}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Radius :",
		.rect = (SDL_Rect){.x = 50, .y = 635}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object transparency and shininess",
		.rect = (SDL_Rect){.x = 25, .y = 688}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Transparency :",
		.rect = (SDL_Rect){.x = 50, .y = 750}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Shininess :",
		.rect = (SDL_Rect){.x = 50, .y = 810}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Textures :",
		.rect = (SDL_Rect){.x = 50, .y = 870}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Filters :",
		.rect = (SDL_Rect){.x = 50, .y = 930}},
};

# define PLANE_TEXT		(17)

static const t_text g_plane_p_text[PLANE_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
		.text = "P lane",
		.rect = (SDL_Rect){.x = 85, .y = 140}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object position",
		.rect = (SDL_Rect){.x = 25, .y = 220}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Position :",
		.rect = (SDL_Rect){.x = 50, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "x",
		.rect = (SDL_Rect){.x = 200, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "y",
		.rect = (SDL_Rect){.x = 300, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "z",
		.rect = (SDL_Rect){.x = 400, .y = 280}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object colors",
		.rect = (SDL_Rect){.x = 25, .y = 335}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Ambient Color :",
		.rect = (SDL_Rect){.x = 50, .y = 400}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Diffuse Color :",
		.rect = (SDL_Rect){.x = 50, .y = 460}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Speculaire Color :",
		.rect = (SDL_Rect){.x = 50, .y = 517}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object radius",
		.rect = (SDL_Rect){.x = 25, .y = 570}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Radius :",
		.rect = (SDL_Rect){.x = 50, .y = 635}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object transparency and shininess",
		.rect = (SDL_Rect){.x = 25, .y = 688}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Transparency :",
		.rect = (SDL_Rect){.x = 50, .y = 750}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Shininess :",
		.rect = (SDL_Rect){.x = 50, .y = 810}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Textures :",
		.rect = (SDL_Rect){.x = 50, .y = 870}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Filters :",
		.rect = (SDL_Rect){.x = 50, .y = 930}},
};

# define CONE_TEXT		(18)

static const t_text g_cone_p_text[CONE_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
		.text = "Cone",
		.rect = (SDL_Rect){.x = 85, .y = 140}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object position",
		.rect = (SDL_Rect){.x = 25, .y = 220}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Position :",
		.rect = (SDL_Rect){.x = 50, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "x",
		.rect = (SDL_Rect){.x = 200, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "y",
		.rect = (SDL_Rect){.x = 300, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "z",
		.rect = (SDL_Rect){.x = 400, .y = 280}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object colors",
		.rect = (SDL_Rect){.x = 25, .y = 335}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Ambient Color :",
		.rect = (SDL_Rect){.x = 50, .y = 400}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Diffuse Color :",
		.rect = (SDL_Rect){.x = 50, .y = 460}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Speculaire Color :",
		.rect = (SDL_Rect){.x = 50, .y = 517}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object radius and alpha",
		.rect = (SDL_Rect){.x = 25, .y = 570}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Radius :",
		.rect = (SDL_Rect){.x = 50, .y = 635}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Alpha :",
		.rect = (SDL_Rect){.x = 50, .y = 690}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object transparency and shininess",
		.rect = (SDL_Rect){.x = 25, .y = 745}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Transparency :",
		.rect = (SDL_Rect){.x = 50, .y = 810}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Shininess :",
		.rect = (SDL_Rect){.x = 50, .y = 870}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Textures :",
		.rect = (SDL_Rect){.x = 50, .y = 930}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Filters :",
		.rect = (SDL_Rect){.x = 50, .y = 985}},
};

# define DISK_TEXT		(17)

static const t_text g_disk_p_text[DISK_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
		.text = "Disk",
		.rect = (SDL_Rect){.x = 85, .y = 140}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object position",
		.rect = (SDL_Rect){.x = 25, .y = 220}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Position :",
		.rect = (SDL_Rect){.x = 50, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "x",
		.rect = (SDL_Rect){.x = 200, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "y",
		.rect = (SDL_Rect){.x = 300, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "z",
		.rect = (SDL_Rect){.x = 400, .y = 280}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object colors",
		.rect = (SDL_Rect){.x = 25, .y = 335}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Ambient Color :",
		.rect = (SDL_Rect){.x = 50, .y = 400}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Diffuse Color :",
		.rect = (SDL_Rect){.x = 50, .y = 460}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Speculaire Color :",
		.rect = (SDL_Rect){.x = 50, .y = 517}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object radius",
		.rect = (SDL_Rect){.x = 25, .y = 570}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Radius :",
		.rect = (SDL_Rect){.x = 50, .y = 635}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object transparency and shininess",
		.rect = (SDL_Rect){.x = 25, .y = 688}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Transparency :",
		.rect = (SDL_Rect){.x = 50, .y = 750}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Shininess :",
		.rect = (SDL_Rect){.x = 50, .y = 810}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Textures :",
		.rect = (SDL_Rect){.x = 50, .y = 870}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Filters :",
		.rect = (SDL_Rect){.x = 50, .y = 930}},
};

# define SPHERE_TEXT		(17)

static const t_text g_sphere_p_text[SPHERE_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
		.text = "Sphere",
		.rect = (SDL_Rect){.x = 85, .y = 140}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object position",
		.rect = (SDL_Rect){.x = 25, .y = 220}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Position :",
		.rect = (SDL_Rect){.x = 50, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "x",
		.rect = (SDL_Rect){.x = 200, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "y",
		.rect = (SDL_Rect){.x = 300, .y = 280}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "z",
		.rect = (SDL_Rect){.x = 400, .y = 280}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object colors",
		.rect = (SDL_Rect){.x = 25, .y = 335}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Ambient Color :",
		.rect = (SDL_Rect){.x = 50, .y = 400}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Diffuse Color :",
		.rect = (SDL_Rect){.x = 50, .y = 460}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Speculaire Color :",
		.rect = (SDL_Rect){.x = 50, .y = 517}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object radius",
		.rect = (SDL_Rect){.x = 25, .y = 570}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Radius :",
		.rect = (SDL_Rect){.x = 50, .y = 635}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Choose your object transparency and shininess",
		.rect = (SDL_Rect){.x = 25, .y = 688}},

	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Transparency :",
		.rect = (SDL_Rect){.x = 50, .y = 750}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Shininess :",
		.rect = (SDL_Rect){.x = 50, .y = 810}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Textures :",
		.rect = (SDL_Rect){.x = 50, .y = 870}},
	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
		.text = "Choose Filters :",
		.rect = (SDL_Rect){.x = 50, .y = 930}},
};

/*
** # define LIGHT_TEXT		(15)
**
** static const t_text g_light_text[LIGHT_TEXT] = {
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
** 		.text = "Light Spots",
** 		.rect = (SDL_Rect){.x = 85, .y = 140}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light position",
** 		.rect = (SDL_Rect){.x = 25, .y = 220}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Position :",
** 		.rect = (SDL_Rect){.x = 50, .y = 280}},
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "x",
** 		.rect = (SDL_Rect){.x = 200, .y = 280}},
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "y",
** 		.rect = (SDL_Rect){.x = 300, .y = 280}},
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "z",
** 		.rect = (SDL_Rect){.x = 400, .y = 280}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light colors",
** 		.rect = (SDL_Rect){.x = 25, .y = 335}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Color :",
** 		.rect = (SDL_Rect){.x = 50, .y = 400}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light radius",
** 		.rect = (SDL_Rect){.x = 25, .y = 453}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Radius :",
** 		.rect = (SDL_Rect){.x = 50, .y = 517}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light intensity",
** 		.rect = (SDL_Rect){.x = 25, .y = 570}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Intensity :",
** 		.rect = (SDL_Rect){.x = 50, .y = 635}},
** };
**
** # define AMBIENT_TEXT		(5)
**
** static const t_text g_ambient_text[AMBIENT_TEXT] = {
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
** 		.text = "Ambient Light",
** 		.rect = (SDL_Rect){.x = 85, .y = 140}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light colors",
** 		.rect = (SDL_Rect){.x = 25, .y = 220}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Color :",
** 		.rect = (SDL_Rect){.x = 50, .y = 280}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light intensity",
** 		.rect = (SDL_Rect){.x = 25, .y = 335}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Intensity :",
** 		.rect = (SDL_Rect){.x = 50, .y = 400}},
** };
**
** # define SUN_TEXT		(10)
**
** static const t_text g_sun_p_text[SUN_TEXT] = {
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
** 		.text = "Sun Light",
** 		.rect = (SDL_Rect){.x = 85, .y = 140}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light direction",
** 		.rect = (SDL_Rect){.x = 25, .y = 220}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Direction :",
** 		.rect = (SDL_Rect){.x = 50, .y = 280}},
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "x",
** 		.rect = (SDL_Rect){.x = 200, .y = 280}},
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "y",
** 		.rect = (SDL_Rect){.x = 300, .y = 280}},
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "z",
** 		.rect = (SDL_Rect){.x = 400, .y = 280}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light colors",
** 		.rect = (SDL_Rect){.x = 25, .y = 335}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Color :",
** 		.rect = (SDL_Rect){.x = 50, .y = 400}},
**
** 	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
** 		.text = "Choose your light intensity",
** 		.rect = (SDL_Rect){.x = 25, .y = 453}},
**
** 	(t_text){.font = "./srcs/utils/KIN668.ttf", .size = 15,
** 		.text = "Intensity :",
** 		.rect = (SDL_Rect){.x = 50, .y = 517}},
** };
*/

# define OTHER_TEXT		(3)

static const t_text g_other_p_text[OTHER_TEXT] = {
	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 30,
		.text = "More Options",
		.rect = (SDL_Rect){.x = 85, .y = 140}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Take a Screenshot :",
		.rect = (SDL_Rect){.x = 25, .y = 220}},

	(t_text){.font = "./srcs/utils/ProDisplay_Regular.ttf", .size = 25,
		.text = "Export to Xml :",
		.rect = (SDL_Rect){.x = 25, .y = 563}},
};

enum			e_button
{
	HOME,
	I_SCENE,
	CHEVRON_R,
	CHEVRON_L,
	HUIT,
	SEPT,
	CINQ,
	QUATRE,
	HOME_CAMERA,
	HOME_EDIT,
	BACK,
	SHAPES,
	I_CYLINDER,
	I_PLANE,
	I_CONE,
	I_DISK,
	I_SPHERE,
	PENCIL,
	LINE,
	MORE,
	LESS,
	RED,
	GREEN,
	BLUE,
	I_RADIUS,
	I_ALPHA,
	I_TRANSPARENCY,
	I_SHININESS,
	BDP,
	CHECKER,
	LIGHT,
	LIGHT1,
	I_INTENSITY,
	AMBIENT_P,
	SUN_P,
	OTHER_P,
	OTHER_I,
	FOV_P,
	LUM_ADD,
	OTHER_ADD,
	FORMS_ADD,
	REFRESH,
	SCREENSHOT,
	PARSER,
	NORMAL_T,
	BLUR,
	BOLD,
	CONTOUR,
	CONTOURL,
	RELIEF,
	ARROW_UP,
	CARTOON,
	BW,
	TEXTURES,
	BUTTON_ALL
};

static const t_picture g_button[BUTTON_ALL] = {
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/home.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/home_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/scene.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/scene.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/chevron_r.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/chevron_r_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/chevron_l.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/chevron_l_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/8.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/8_2.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/7.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/7_2.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/5.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/5_2.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/4.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/4_2.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/camera.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/camera.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/edit.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/edit.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/back.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/back.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/shapes.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/shapes.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/cylinder.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/cylinder.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/plane.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/plane.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/cone.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/cone.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/disk.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/disk.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/sphere.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/sphere.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/pencil.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/pencil.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/line.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/line.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/more.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/more_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/less.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/less_r.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/red.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/red.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/green.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/green.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/blue.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/blue.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/radius.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/radius.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/alpha.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/alpha.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/transparency_v.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/transparency_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/shininess_v.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/shininess_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/bdp.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/bdp_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/checker.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/checker_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/light.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/light.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/i_light.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/i_light.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/intensity.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/intensity.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/ambient.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/ambient.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/sun.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/sun.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/other_p.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/other_p.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/code.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/code.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/angle.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/angle.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/lum.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/lum_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/other.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/other_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/formes.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/formes_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/refresh.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/print.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/screenshot.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/screenshot_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/parser.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/parser_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/normal.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/normal_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/blur.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/blur_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/bold.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/bold_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/contour.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/contour_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/contourl.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/contourl_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/relief.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/relief_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/arrow_up.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/arrow_up_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/cartoon.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/cartoon_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/bw.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/bw_v.png"},
	(t_picture){.n_type = TYPE_PNG,
		.n_path = "./srcs/utils/textures.png", .h_type = TYPE_PNG,
		.h_path = "./srcs/utils/textures_v.png"},
};

typedef struct	s_rectangle
{
	int			id;
	int			value;
	float		pitch;
	SDL_Rect	position;
}				t_rectangle;

# define HOME_BUTTON		(8)

static const t_rectangle g_home_button[HOME_BUTTON] = {
	(t_rectangle){.id = I_SCENE, .value = -1,
		.position = (SDL_Rect){.x = 230, .y = 290, .w = 128, .h = 128}},
	(t_rectangle){.id = HUIT, .value = V_CUR_SCENE, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 325, .w = 64, .h = 64}},
	(t_rectangle){.id = SEPT, .value = V_CUR_SCENE, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 325, .w = 64, .h = 64}},
	(t_rectangle){.id = HOME_CAMERA, .value = -1,
		.position = (SDL_Rect){.x = 230, .y = 560, .w = 128, .h = 128}},
	(t_rectangle){.id = CINQ, .value = V_CUR_CAM, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 585, .w = 64, .h = 64}},
	(t_rectangle){.id = QUATRE, .value = V_CUR_CAM, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 585, .w = 64, .h = 64}},
	(t_rectangle){.id = HOME_EDIT, .value = V_GO_EDIT,
		.position = (SDL_Rect){.x = 240, .y = 815, .w = 128, .h = 128}},
	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},
};

# define ADD_BUTTON		(5)

static const t_rectangle g_add_button[ADD_BUTTON] = {
	(t_rectangle){.id = HOME, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
	(t_rectangle){.id = FORMS_ADD, .value = V_GO_OBJECT,
		.position = (SDL_Rect){.x = 50, .y = 200, .w = 128, .h = 128}},
	(t_rectangle){.id = LUM_ADD, .value = V_GO_LIGHT,
		.position = (SDL_Rect){.x = 410, .y = 510, .w = 128, .h = 128}},
	(t_rectangle){.id = OTHER_ADD, .value = V_GO_OTHER,
		.position = (SDL_Rect){.x = 50, .y = 825, .w = 128, .h = 128}},
	(t_rectangle){.id = BACK, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 550, .y = 1040, .w = 32, .h = 32}}};

# define CYLINDER_BUTTON		(63)

static const t_rectangle g_cylinder_p_button[CYLINDER_BUTTON] = {
	(t_rectangle){.id = HOME, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
	(t_rectangle){.id = SHAPES, .value = -1,
		.position = (SDL_Rect){.x = 220, .y = 15, .w = 128, .h = 128}},
	(t_rectangle){.id = I_CYLINDER, .value = -1,
		.position = (SDL_Rect){.x = 10, .y = 120, .w = 64, .h = 64}},
	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_OBJ, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_OBJ, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},

	(t_rectangle){.id = MORE, .value = VO_POS_X, .pitch = 5,
		.position = (SDL_Rect){.x = 215, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_X, .pitch = -5,
		.position = (SDL_Rect){.x = 170, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Y, .pitch = 5,
		.position = (SDL_Rect){.x = 315, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Y, .pitch = -5,
		.position = (SDL_Rect){.x = 270, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Z, .pitch = 5,
		.position = (SDL_Rect){.x = 415, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Z, .pitch = -5,
		.position = (SDL_Rect){.x = 370, .y = 275, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 390, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 450, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 253, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 290, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 225, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 373, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 410, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 345, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 493, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 530, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 465, .y = 507, .w = 24, .h = 24}},

	(t_rectangle){.id = PENCIL, .value = -1,
		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
	(t_rectangle){.id = LINE, .value = -1,
		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},

	(t_rectangle){.id = I_RADIUS, .value = -1,
		.position = (SDL_Rect){.x = 190, .y = 620, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_RAY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 235, .y = 625, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_RAY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 150, .y = 625, .w = 24, .h = 24}},

	(t_rectangle){.id = I_TRANSPARENCY, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 735, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_TRANSPARENCY, .pitch = 0.1,
		.position = (SDL_Rect){.x = 270, .y = 740, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_TRANSPARENCY, .pitch = -0.1,
		.position = (SDL_Rect){.x = 185, .y = 740, .w = 24, .h = 24}},

	(t_rectangle){.id = I_SHININESS, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 795, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SHININESS, .pitch = -1,
		.position = (SDL_Rect){.x = 270, .y = 800, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SHININESS, .pitch = 1,
		.position = (SDL_Rect){.x = 185, .y = 800, .w = 24, .h = 24}},

	(t_rectangle){.id = CHECKER, .value = VT_CHECKER,
		.position = (SDL_Rect){.x = 250, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = TEXTURES, .value = VT_TEXTURE,
		.position = (SDL_Rect){.x = 210, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = BDP, .value = VT_PERLIN,
		.position = (SDL_Rect){.x = 290, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = NORMAL_T, .value = VT_NORMAL,
		.position = (SDL_Rect){.x = 330, .y = 855, .w = 32, .h = 32}},

	(t_rectangle){.id = BLUR, .value = VT_BLUR_BOX,
		.position = (SDL_Rect){.x = 200, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BOLD, .value = VT_SHARPEN,
		.position = (SDL_Rect){.x = 240, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOUR, .value = VT_EDGE_HARD,
		.position = (SDL_Rect){.x = 280, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOURL, .value = VT_SEPIA,
		.position = (SDL_Rect){.x = 320, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = RELIEF, .value = VT_EMBOSSING,
		.position = (SDL_Rect){.x = 360, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = ARROW_UP, .value = VT_ANTIALIAZ,
		.position = (SDL_Rect){.x = 400, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CARTOON, .value = VT_CARTOON,
		.position = (SDL_Rect){.x = 440, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BW, .value = VT_BLACK_WHITE,
		.position = (SDL_Rect){.x = 480, .y = 915, .w = 32, .h = 32}},
};

# define PLANE_BUTTON		(63)

static const t_rectangle g_plane_p_button[PLANE_BUTTON] = {
	(t_rectangle){.id = HOME, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
	(t_rectangle){.id = SHAPES, .value = -1,
		.position = (SDL_Rect){.x = 220, .y = 15, .w = 128, .h = 128}},
	(t_rectangle){.id = I_PLANE, .value = -1,
		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_OBJ, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_OBJ, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},

	(t_rectangle){.id = MORE, .value = VO_POS_X, .pitch = 0.5,
		.position = (SDL_Rect){.x = 215, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_X, .pitch = -0.5,
		.position = (SDL_Rect){.x = 170, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Y, .pitch = 0.5,
		.position = (SDL_Rect){.x = 315, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Y, .pitch = -0.5,
		.position = (SDL_Rect){.x = 270, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Z, .pitch = 0.5,
		.position = (SDL_Rect){.x = 415, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Z, .pitch = -0.5,
		.position = (SDL_Rect){.x = 370, .y = 275, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 390, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 450, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 253, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 290, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 225, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 373, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 410, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 345, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 493, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 530, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 465, .y = 507, .w = 24, .h = 24}},

	(t_rectangle){.id = PENCIL, .value = -1,
		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
	(t_rectangle){.id = LINE, .value = -1,
		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},

	(t_rectangle){.id = I_RADIUS, .value = -1,
		.position = (SDL_Rect){.x = 190, .y = 620, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_RAY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 235, .y = 625, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_RAY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 150, .y = 625, .w = 24, .h = 24}},

	(t_rectangle){.id = I_TRANSPARENCY, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 735, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_TRANSPARENCY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 270, .y = 740, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_TRANSPARENCY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 185, .y = 740, .w = 24, .h = 24}},

	(t_rectangle){.id = I_SHININESS, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 795, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SHININESS, .pitch = -1,
		.position = (SDL_Rect){.x = 270, .y = 800, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SHININESS, .pitch = 1,
		.position = (SDL_Rect){.x = 185, .y = 800, .w = 24, .h = 24}},

	(t_rectangle){.id = BDP, .value = VT_PERLIN,
		.position = (SDL_Rect){.x = 290, .y = 855, .w = 32, .h = 32}},

	(t_rectangle){.id = CHECKER, .value = VT_CHECKER,
		.position = (SDL_Rect){.x = 250, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = TEXTURES, .value = VT_TEXTURE,
		.position = (SDL_Rect){.x = 210, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = NORMAL_T, .value = VT_NORMAL,
		.position = (SDL_Rect){.x = 330, .y = 855, .w = 32, .h = 32}},

	(t_rectangle){.id = BLUR, .value = VT_BLUR_BOX,
		.position = (SDL_Rect){.x = 200, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BOLD, .value = VT_SHARPEN,
		.position = (SDL_Rect){.x = 240, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOUR, .value = VT_EDGE_HARD,
		.position = (SDL_Rect){.x = 280, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOURL, .value = VT_SEPIA,
		.position = (SDL_Rect){.x = 320, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = RELIEF, .value = VT_EMBOSSING,
		.position = (SDL_Rect){.x = 360, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = ARROW_UP, .value = VT_ANTIALIAZ,
		.position = (SDL_Rect){.x = 400, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CARTOON, .value = VT_CARTOON,
		.position = (SDL_Rect){.x = 440, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BW, .value = VT_BLACK_WHITE,
		.position = (SDL_Rect){.x = 480, .y = 915, .w = 32, .h = 32}},

};

# define CONE_BUTTON		(66)

static const t_rectangle g_cone_p_button[CONE_BUTTON] = {
	(t_rectangle){.id = HOME, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
	(t_rectangle){.id = SHAPES, .value = -1,
		.position = (SDL_Rect){.x = 220, .y = 15, .w = 128, .h = 128}},
	(t_rectangle){.id = I_CONE, .value = -1,
		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_OBJ, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_OBJ, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},

	(t_rectangle){.id = MORE, .value = VO_POS_X, .pitch = 0.5,
		.position = (SDL_Rect){.x = 215, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_X, .pitch = -0.5,
		.position = (SDL_Rect){.x = 170, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Y, .pitch = 0.5,
		.position = (SDL_Rect){.x = 315, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Y, .pitch = -0.5,
		.position = (SDL_Rect){.x = 270, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Z, .pitch = 0.5,
		.position = (SDL_Rect){.x = 415, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Z, .pitch = -0.5,
		.position = (SDL_Rect){.x = 370, .y = 275, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 390, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 450, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 253, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 290, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 225, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 373, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 410, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 345, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 493, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 530, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 465, .y = 507, .w = 24, .h = 24}},

	(t_rectangle){.id = PENCIL, .value = -1,
		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
	(t_rectangle){.id = LINE, .value = -1,
		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},

	(t_rectangle){.id = I_RADIUS, .value = -1,
		.position = (SDL_Rect){.x = 190, .y = 620, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_RAY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 235, .y = 625, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_RAY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 150, .y = 625, .w = 24, .h = 24}},

	(t_rectangle){.id = I_ALPHA, .value = -1,
		.position = (SDL_Rect){.x = 190, .y = 680, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_ALPHA, .pitch = 0.05,
		.position = (SDL_Rect){.x = 235, .y = 685, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_ALPHA, .pitch = -0.05,
		.position = (SDL_Rect){.x = 150, .y = 685, .w = 24, .h = 24}},

	(t_rectangle){.id = I_TRANSPARENCY, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 795, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_TRANSPARENCY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 270, .y = 800, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_TRANSPARENCY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 185, .y = 800, .w = 24, .h = 24}},

	(t_rectangle){.id = I_SHININESS, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SHININESS, .pitch = -1,
		.position = (SDL_Rect){.x = 270, .y = 860, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SHININESS, .pitch = 1,
		.position = (SDL_Rect){.x = 185, .y = 860, .w = 24, .h = 24}},

	(t_rectangle){.id = BDP, .value = VT_PERLIN,
		.position = (SDL_Rect){.x = 290, .y = 910, .w = 32, .h = 32}},

	(t_rectangle){.id = CHECKER, .value = VT_CHECKER,
		.position = (SDL_Rect){.x = 250, .y = 910, .w = 32, .h = 32}},
	(t_rectangle){.id = TEXTURES, .value = VT_TEXTURE,
		.position = (SDL_Rect){.x = 210, .y = 910, .w = 32, .h = 32}},
	(t_rectangle){.id = NORMAL_T, .value = VT_NORMAL,
		.position = (SDL_Rect){.x = 330, .y = 910, .w = 32, .h = 32}},

	(t_rectangle){.id = BLUR, .value = VT_BLUR_BOX,
		.position = (SDL_Rect){.x = 200, .y = 970, .w = 32, .h = 32}},
	(t_rectangle){.id = BOLD, .value = VT_SHARPEN,
		.position = (SDL_Rect){.x = 240, .y = 970, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOUR, .value = VT_EDGE_HARD,
		.position = (SDL_Rect){.x = 280, .y = 970, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOURL, .value = VT_SEPIA,
		.position = (SDL_Rect){.x = 320, .y = 970, .w = 32, .h = 32}},
	(t_rectangle){.id = RELIEF, .value = VT_EMBOSSING,
		.position = (SDL_Rect){.x = 360, .y = 970, .w = 32, .h = 32}},
	(t_rectangle){.id = ARROW_UP, .value = VT_ANTIALIAZ,
		.position = (SDL_Rect){.x = 400, .y = 970, .w = 32, .h = 32}},
	(t_rectangle){.id = CARTOON, .value = VT_CARTOON,
		.position = (SDL_Rect){.x = 440, .y = 970, .w = 32, .h = 32}},
	(t_rectangle){.id = BW, .value = VT_BLACK_WHITE,
		.position = (SDL_Rect){.x = 480, .y = 970, .w = 32, .h = 32}},
};

# define DISK_BUTTON		(63)

static const t_rectangle g_disk_p_button[DISK_BUTTON] = {
	(t_rectangle){.id = HOME, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
	(t_rectangle){.id = SHAPES, .value = -1,
		.position = (SDL_Rect){.x = 220, .y = 15, .w = 128, .h = 128}},
	(t_rectangle){.id = I_DISK, .value = -1,
		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_OBJ, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_OBJ, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},

	(t_rectangle){.id = MORE, .value = VO_POS_X, .pitch = 0.5,
		.position = (SDL_Rect){.x = 215, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_X, .pitch = -0.5,
		.position = (SDL_Rect){.x = 170, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Y, .pitch = 0.5,
		.position = (SDL_Rect){.x = 315, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Y, .pitch = -0.5,
		.position = (SDL_Rect){.x = 270, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Z, .pitch = 0.5,
		.position = (SDL_Rect){.x = 415, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Z, .pitch = -0.5,
		.position = (SDL_Rect){.x = 370, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 450, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 253, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 290, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 225, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 373, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 410, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 345, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 493, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 530, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 465, .y = 507, .w = 24, .h = 24}},

	(t_rectangle){.id = PENCIL, .value = -1,
		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
	(t_rectangle){.id = LINE, .value = -1,
		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},

	(t_rectangle){.id = I_RADIUS, .value = -1,
		.position = (SDL_Rect){.x = 190, .y = 620, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_RAY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 235, .y = 625, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_RAY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 150, .y = 625, .w = 24, .h = 24}},

	(t_rectangle){.id = I_TRANSPARENCY, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 735, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_TRANSPARENCY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 270, .y = 740, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_TRANSPARENCY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 185, .y = 740, .w = 24, .h = 24}},

	(t_rectangle){.id = I_SHININESS, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 795, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SHININESS, .pitch = -1,
		.position = (SDL_Rect){.x = 270, .y = 800, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SHININESS, .pitch = 1,
		.position = (SDL_Rect){.x = 185, .y = 800, .w = 24, .h = 24}},

	(t_rectangle){.id = BDP, .value = VT_PERLIN,
		.position = (SDL_Rect){.x = 290, .y = 855, .w = 32, .h = 32}},

	(t_rectangle){.id = CHECKER, .value = VT_CHECKER,
		.position = (SDL_Rect){.x = 250, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = TEXTURES, .value = VT_TEXTURE,
		.position = (SDL_Rect){.x = 210, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = NORMAL_T, .value = VT_NORMAL,
		.position = (SDL_Rect){.x = 330, .y = 855, .w = 32, .h = 32}},

	(t_rectangle){.id = BLUR, .value = VT_BLUR_BOX,
		.position = (SDL_Rect){.x = 200, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BOLD, .value = VT_SHARPEN,
		.position = (SDL_Rect){.x = 240, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOUR, .value = VT_EDGE_HARD,
		.position = (SDL_Rect){.x = 280, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOURL, .value = VT_SEPIA,
		.position = (SDL_Rect){.x = 320, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = RELIEF, .value = VT_EMBOSSING,
		.position = (SDL_Rect){.x = 360, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = ARROW_UP, .value = VT_ANTIALIAZ,
		.position = (SDL_Rect){.x = 400, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CARTOON, .value = VT_CARTOON,
		.position = (SDL_Rect){.x = 440, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BW, .value = VT_BLACK_WHITE,
		.position = (SDL_Rect){.x = 480, .y = 915, .w = 32, .h = 32}},
};

# define SPHERE_BUTTON		(63)

static const t_rectangle g_sphere_p_button[SPHERE_BUTTON] = {
	(t_rectangle){.id = HOME, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
	(t_rectangle){.id = SHAPES, .value = -1,
		.position = (SDL_Rect){.x = 220, .y = 15, .w = 128, .h = 128}},
	(t_rectangle){.id = I_SPHERE, .value = -1,
		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_OBJ, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_OBJ, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},

	(t_rectangle){.id = MORE, .value = VO_POS_X, .pitch = 0.5,
		.position = (SDL_Rect){.x = 215, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_X, .pitch = -0.5,
		.position = (SDL_Rect){.x = 170, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Y, .pitch = 0.5,
		.position = (SDL_Rect){.x = 315, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Y, .pitch = -0.5,
		.position = (SDL_Rect){.x = 270, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = MORE, .value = VO_POS_Z, .pitch = 0.5,
		.position = (SDL_Rect){.x = 415, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_POS_Z, .pitch = -0.5,
		.position = (SDL_Rect){.x = 370, .y = 275, .w = 24, .h = 24}},
	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 390, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_AMBIENT_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 390, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_AMBIENT_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 390, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 223, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 260, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 195, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 343, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 380, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 315, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 463, .y = 450, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_DIFFUSE_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 500, .y = 450, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_DIFFUSE_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 435, .y = 450, .w = 24, .h = 24}},

	(t_rectangle){.id = RED, .value = -1,
		.position = (SDL_Rect){.x = 253, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_RED, .pitch = 0.05,
		.position = (SDL_Rect){.x = 290, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_RED, .pitch = -0.05,
		.position = (SDL_Rect){.x = 225, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = GREEN, .value = -1,
		.position = (SDL_Rect){.x = 373, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_GREEN, .pitch = 0.05,
		.position = (SDL_Rect){.x = 410, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_GREEN, .pitch = -0.05,
		.position = (SDL_Rect){.x = 345, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = BLUE, .value = -1,
		.position = (SDL_Rect){.x = 493, .y = 507, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SPECULAR_BLUE, .pitch = 0.05,
		.position = (SDL_Rect){.x = 530, .y = 507, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SPECULAR_BLUE, .pitch = -0.05,
		.position = (SDL_Rect){.x = 465, .y = 507, .w = 24, .h = 24}},

	(t_rectangle){.id = PENCIL, .value = -1,
		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
	(t_rectangle){.id = LINE, .value = -1,
		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},

	(t_rectangle){.id = I_RADIUS, .value = -1,
		.position = (SDL_Rect){.x = 190, .y = 620, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_RAY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 235, .y = 625, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_RAY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 150, .y = 625, .w = 24, .h = 24}},

	(t_rectangle){.id = I_TRANSPARENCY, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 735, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_TRANSPARENCY, .pitch = 0.05,
		.position = (SDL_Rect){.x = 270, .y = 740, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_TRANSPARENCY, .pitch = -0.05,
		.position = (SDL_Rect){.x = 185, .y = 740, .w = 24, .h = 24}},

	(t_rectangle){.id = I_SHININESS, .value = -1,
		.position = (SDL_Rect){.x = 225, .y = 795, .w = 32, .h = 32}},
	(t_rectangle){.id = MORE, .value = VO_SHININESS, .pitch = -1,
		.position = (SDL_Rect){.x = 270, .y = 800, .w = 24, .h = 24}},
	(t_rectangle){.id = LESS, .value = VO_SHININESS, .pitch = 1,
		.position = (SDL_Rect){.x = 185, .y = 800, .w = 24, .h = 24}},

	(t_rectangle){.id = BDP, .value = VT_PERLIN,
		.position = (SDL_Rect){.x = 290, .y = 855, .w = 32, .h = 32}},

	(t_rectangle){.id = CHECKER, .value = VT_CHECKER,
		.position = (SDL_Rect){.x = 250, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = TEXTURES, .value = VT_TEXTURE,
		.position = (SDL_Rect){.x = 210, .y = 855, .w = 32, .h = 32}},
	(t_rectangle){.id = NORMAL_T, .value = VT_NORMAL,
		.position = (SDL_Rect){.x = 330, .y = 855, .w = 32, .h = 32}},

	(t_rectangle){.id = BLUR, .value = VT_BLUR_BOX,
		.position = (SDL_Rect){.x = 200, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BOLD, .value = VT_SHARPEN,
		.position = (SDL_Rect){.x = 240, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOUR, .value = VT_EDGE_HARD,
		.position = (SDL_Rect){.x = 280, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CONTOURL, .value = VT_SEPIA,
		.position = (SDL_Rect){.x = 320, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = RELIEF, .value = VT_EMBOSSING,
		.position = (SDL_Rect){.x = 360, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = ARROW_UP, .value = VT_ANTIALIAZ,
		.position = (SDL_Rect){.x = 400, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = CARTOON, .value = VT_CARTOON,
		.position = (SDL_Rect){.x = 440, .y = 915, .w = 32, .h = 32}},
	(t_rectangle){.id = BW, .value = VT_BLACK_WHITE,
		.position = (SDL_Rect){.x = 480, .y = 915, .w = 32, .h = 32}},

};

/*
** # define LIGHT_BUTTON		(30)
**
** static const t_rectangle g_light_button[LIGHT_BUTTON] = {
** 	(t_rectangle){.id = HOME, .value = V_GO_HOME,
** 		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
** 	(t_rectangle){.id = LIGHT, .value = -1,
** 		.position = (SDL_Rect){.x = 220, .y = 35, .w = 128, .h = 128}},
** 	(t_rectangle){.id = LIGHT1, .value = -1,
** 		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
** 	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_LIGHT, .pitch = 1,
** 		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
** 	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_LIGHT, .pitch = -1,
** 		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},
**
** 	(t_rectangle){.id = MORE, .value = VL_POS_X, .pitch = 2,
** 		.position = (SDL_Rect){.x = 215, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_POS_X, .pitch = -2,
** 		.position = (SDL_Rect){.x = 170, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = MORE, .value = VL_POS_Y, .pitch = 2,
** 		.position = (SDL_Rect){.x = 315, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_POS_Y, .pitch = -2,
** 		.position = (SDL_Rect){.x = 270, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = MORE, .value = VL_POS_Z, .pitch = 2,
** 		.position = (SDL_Rect){.x = 415, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_POS_Z, .pitch = -2,
** 		.position = (SDL_Rect){.x = 370, .y = 275, .w = 24, .h = 24}},
**
** 	(t_rectangle){.id = RED, .value = -1,
** 		.position = (SDL_Rect){.x = 173, .y = 390, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_RED, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 210, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_RED, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 145, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = GREEN, .value = -1,
** 		.position = (SDL_Rect){.x = 293, .y = 390, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_GREEN, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 330, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_GREEN, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 265, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = BLUE, .value = -1,
** 		.position = (SDL_Rect){.x = 413, .y = 390, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_BLUE, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 450, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_BLUE, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 385, .y = 390, .w = 24, .h = 24}},
**
** 	(t_rectangle){.id = PENCIL, .value = -1,
** 		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
** 	(t_rectangle){.id = LINE, .value = -1,
** 		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
** 	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
** 		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
** 	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
** 		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},
**
** 	(t_rectangle){.id = I_RADIUS, .value = -1,
** 		.position = (SDL_Rect){.x = 190, .y = 500, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_RAY, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 235, .y = 507, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_RAY, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 150, .y = 507, .w = 24, .h = 24}},
**
** 	(t_rectangle){.id = I_INTENSITY, .value = -1,
** 		.position = (SDL_Rect){.x = 205, .y = 620, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_INTENSITY, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 250, .y = 625, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_INTENSITY, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 165, .y = 625, .w = 24, .h = 24}},
**
** };
**
** # define AMBIENT_BUTTON		(21)
**
** static const t_rectangle g_ambient_button[AMBIENT_BUTTON] = {
** 	(t_rectangle){.id = HOME, .value = V_GO_HOME,
** 		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
** 	(t_rectangle){.id = LIGHT, .value = -1,
** 		.position = (SDL_Rect){.x = 220, .y = 35, .w = 128, .h = 128}},
** 	(t_rectangle){.id = AMBIENT_P, .value = -1,
** 		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
** 	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_LIGHT, .pitch = 1,
** 		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
** 	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_LIGHT, .pitch = -1,
** 		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},
**
** 	(t_rectangle){.id = RED, .value = -1,
** 		.position = (SDL_Rect){.x = 173, .y = 275, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_RED, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 210, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_RED, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 145, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = GREEN, .value = -1,
** 		.position = (SDL_Rect){.x = 293, .y = 275, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, VL_COLOR_GREEN, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 330, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_GREEN, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 265, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = BLUE, .value = -1,
** 		.position = (SDL_Rect){.x = 413, .y = 275, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_BLUE, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 450, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_BLUE, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 385, .y = 275, .w = 24, .h = 24}},
**
** 	(t_rectangle){.id = PENCIL, .value = -1,
** 		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
** 	(t_rectangle){.id = LINE, .value = -1,
** 		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
** 	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
** 		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
** 	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
** 		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},
**
** 	(t_rectangle){.id = I_INTENSITY, .value = -1,
** 		.position = (SDL_Rect){.x = 205, .y = 390, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_INTENSITY, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 250, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_INTENSITY, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 165, .y = 390, .w = 24, .h = 24}},
**
** };
**
** # define SUN_BUTTON		(27)
**
** static const t_rectangle g_sun_p_button[SUN_BUTTON] = {
** 	(t_rectangle){.id = HOME, .value = V_GO_HOME,
** 		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
** 	(t_rectangle){.id = LIGHT, .value = -1,
** 		.position = (SDL_Rect){.x = 220, .y = 35, .w = 128, .h = 128}},
** 	(t_rectangle){.id = SUN_P, .value = -1,
** 		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
** 	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_LIGHT, .pitch = 1,
** 		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
** 	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_LIGHT, .pitch = -1,
** 		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},
**
** 	(t_rectangle){.id = MORE, .value = VL_POS_X, .pitch = 0.5,
** 		.position = (SDL_Rect){.x = 215, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_POS_X, .pitch = -0.5,
** 		.position = (SDL_Rect){.x = 170, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = MORE, .value = VL_POS_Y, .pitch = 0.5,
** 		.position = (SDL_Rect){.x = 315, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_POS_Y, .pitch = -0.5,
** 		.position = (SDL_Rect){.x = 270, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = MORE, .value = VL_POS_Z, .pitch = 0.5,
** 		.position = (SDL_Rect){.x = 415, .y = 275, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_POS_Z, .pitch = -0.5,
** 		.position = (SDL_Rect){.x = 370, .y = 275, .w = 24, .h = 24}},
**
** 	(t_rectangle){.id = RED, .value = -1,
** 		.position = (SDL_Rect){.x = 173, .y = 390, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_RED, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 210, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_RED, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 145, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = GREEN, .value = -1,
** 		.position = (SDL_Rect){.x = 293, .y = 390, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_GREEN, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 330, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_GREEN, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 265, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = BLUE, .value = -1,
** 		.position = (SDL_Rect){.x = 413, .y = 390, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_COLOR_BLUE, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 450, .y = 390, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_COLOR_BLUE, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 385, .y = 390, .w = 24, .h = 24}},
**
** 	(t_rectangle){.id = PENCIL, .value = -1,
** 		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
** 	(t_rectangle){.id = LINE, .value = -1,
** 		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
** 	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
** 		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
** 	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
** 		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},
**
** 	(t_rectangle){.id = I_INTENSITY, .value = -1,
** 		.position = (SDL_Rect){.x = 205, .y = 500, .w = 32, .h = 32}},
** 	(t_rectangle){.id = MORE, .value = VL_INTENSITY, .pitch = 0.05,
** 		.position = (SDL_Rect){.x = 250, .y = 507, .w = 24, .h = 24}},
** 	(t_rectangle){.id = LESS, .value = VL_INTENSITY, .pitch = -0.05,
** 		.position = (SDL_Rect){.x = 165, .y = 507, .w = 24, .h = 24}},
** };
*/

# define OTHER_BUTTON		(11)

static const t_rectangle g_other_p_button[OTHER_BUTTON] = {
	(t_rectangle){.id = HOME, .value = V_GO_HOME,
		.position = (SDL_Rect){.x = 10, .y = 5, .w = 32, .h = 32}},
	(t_rectangle){.id = OTHER_P, .value = -1,
		.position = (SDL_Rect){.x = 220, .y = 30, .w = 128, .h = 128}},
	(t_rectangle){.id = OTHER_I, .value = -1,
		.position = (SDL_Rect){.x = 15, .y = 120, .w = 64, .h = 64}},
	(t_rectangle){.id = CHEVRON_R, .value = V_CUR_CAM, .pitch = 1,
		.position = (SDL_Rect){.x = 400, .y = 75, .w = 32, .h = 32}},
	(t_rectangle){.id = CHEVRON_L, .value = V_CUR_CAM, .pitch = -1,
		.position = (SDL_Rect){.x = 125, .y = 75, .w = 32, .h = 32}},

	(t_rectangle){.id = PENCIL, .value = -1,
		.position = (SDL_Rect){.x = 551, .y = 156, .w = 32, .h = 32}},
	(t_rectangle){.id = LINE, .value = -1,
		.position = (SDL_Rect){.x = 44, .y = 156, .w = 512, .h = 64}},
	(t_rectangle){.id = BACK, .value = V_GO_EDIT,
		.position = (SDL_Rect){.x = 550, .y = 1030, .w = 32, .h = 32}},
	(t_rectangle){.id = REFRESH, .value = V_REFRESH,
		.position = (SDL_Rect){.x = 550, .y = 5, .w = 32, .h = 32}},

	(t_rectangle){.id = SCREENSHOT, .value = V_TAKE_SCREEN,
		.position = (SDL_Rect){.x = 180, .y = 275, .w = 256, .h = 256}},
	(t_rectangle){.id = PARSER, .value = V_TAKE_XML,
		.position = (SDL_Rect){.x = 200, .y = 675, .w = 256, .h = 256}},
};

typedef struct	s_interface
{
	int					bg;
	const t_text		*text;
	int					s_text;
	const t_rectangle	*button;
	int					s_button;
}				t_interface;

static const t_interface g_interface[INTERFACE_ALL] = {
	(t_interface){.bg = 0,
		.text = g_home_text,
		.s_text = HOME_TEXT,
		.button = g_home_button,
		.s_button = HOME_BUTTON},
	(t_interface){.bg = 1,
		.text = g_add_text,
		.s_text = ADD_TEXT,
		.button = g_add_button,
		.s_button = ADD_BUTTON},
	(t_interface){.bg = 2,
		.text = g_cylinder_p_text,
		.s_text = CYLINDER_TEXT,
		.button = g_cylinder_p_button,
		.s_button = CYLINDER_BUTTON},
	(t_interface){.bg = 2,
		.text = g_plane_p_text,
		.s_text = PLANE_TEXT,
		.button = g_plane_p_button,
		.s_button = PLANE_BUTTON},
	(t_interface){.bg = 2,
		.text = g_cone_p_text,
		.s_text = CONE_TEXT,
		.button = g_cone_p_button,
		.s_button = CONE_BUTTON},
	(t_interface){.bg = 2,
		.text = g_disk_p_text,
		.s_text = DISK_TEXT,
		.button = g_disk_p_button,
		.s_button = DISK_BUTTON},
	(t_interface){.bg = 2,
		.text = g_sphere_p_text,
		.s_text = SPHERE_TEXT,
		.button = g_sphere_p_button,
		.s_button = SPHERE_BUTTON},
/*
** (t_interface){.bg = 2,
** 	.text = g_light_text,
** 	.s_text = LIGHT_TEXT,
** 	.button = g_light_button,
** 	.s_button = LIGHT_BUTTON},
** (t_interface){.bg = 2,
** 	.text = g_ambient_text,
** 	.s_text = AMBIENT_TEXT,
** 	.button = g_ambient_button,
** 	.s_button = AMBIENT_BUTTON},
** (t_interface){.bg = 2,
** 	.text = g_sun_p_text,
** 	.s_text = SUN_TEXT,
** 	.button = g_sun_p_button,
** 	.s_button = SUN_BUTTON},
*/
	(t_interface){.bg = 2,
		.text = g_other_p_text,
		.s_text = OTHER_TEXT,
		.button = g_other_p_button,
		.s_button = OTHER_BUTTON},

};

# define MM_TAN		(1 << 0)
# define MM_LUM		(1 << 1)
# define MM_MIN		(1 << 2)
# define MM_MAX		(1 << 3)

typedef struct	s_min_max
{
	int		flags;
	float	min;
	float	max;
}				t_min_max;

enum			e_min_max
{
	MM_NONE,
	MM_13,
	MM_10,
	MM_EPS,
	MM_1,
	MM_ALPHA,
	MM_10_LUM,
	MIN_MAX_ALL
};

static const t_min_max g_min_max[MIN_MAX_ALL] = {
	(t_min_max){.flags = 0},
	(t_min_max){.flags = MM_MIN | MM_MAX, .min = 1., .max = 3.},
	(t_min_max){.flags = MM_MIN | MM_MAX, .min = 0., .max = 1.},
	(t_min_max){.flags = MM_MIN | MM_MAX, .min = EPSILON, .max = 1000.},
	(t_min_max){.flags = MM_MIN | MM_MAX, .min = 1., .max = 1000.},
	(t_min_max){.flags = MM_TAN},
	(t_min_max){.flags = MM_MIN | MM_MAX | MM_LUM, .min = 0., .max = 1.},
};

#endif
